workflows:
  homekeep-ios:
    name: HomeKeep iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: App Store Connect API Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ai.e6.homekeep
      vars:
        BUNDLE_ID: ai.e6.homekeep
        APP_STORE_CONNECT_ISSUER_ID: 6542e2a9-fff8-4124-9083-2186cad6de0b
        APP_STORE_CONNECT_KEY_IDENTIFIER: 3529W4RQ55
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "HomeKeep.xcodeproj/project.xcworkspace" \
            --scheme "HomeKeep" \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
