name: HomeKeep
options:
  bundleIdPrefix: ai.e6
  deploymentTarget:
    iOS: "17.0"
targets:
  HomeKeep:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "Info.plist"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: HomeKeep
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.e6.homekeep
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
